### ISSUE TITLE
NodeShapes won't load images

### ISSUE THREAD

**Issue by ablikan** [dunnock/react-sigma#73] opened 2019-05-28 18:49 UTC
I suspect it's because initPlugin() is not called in nodes.js, or if it is called, it's without the sigma instance, in any case, sigInst in drawImage always seems to be null.
I can't quite figure out how to call that function to feed it my instance, any hints?

The plugin otherwise works when it comes to supported shapes (square, cross...)

**Comment by dunnock** [comment] 2019-05-29 04:49
Can you actually provide example?

**Comment by jaredkirkley** [comment] 2019-09-06 18:48
Do you have an example of custom images working for nodes?  I'm having a tough time trying to get anywhere with that.

**Comment by uf0** [comment] 2019-09-17 14:15
Hi @jaredkirkley,
do you have a working example?
I'm using your fork and I added a prop `image` to each node like stated here:
https://github.com/jacomyal/sigma.js/tree/master/plugins/sigma.renderers.customShapes#images

but no images appeared

my code looks like this:

```JSX
    <Sigma
      renderer="canvas"
      style={{ width: "100%", height: "100%" }}
      graph={{nodes:[{id:23, label: "20651609",size: 10,x: 501.10980224609375,y: -253.71058654785156,image:{url:"https://a0.muscache.com/im/pictures/a6aa21e9-d03c-4d16-8732-92b2bf891b5e.jpg"}]}}
    >
      <NodeShapes default="circle" />
    </Sigma>
```

**Comment by jaredkirkley** [comment] 2019-09-17 14:50
I am using images that are local to my project which may be the difference.  My urls on my images are like `{ url: '/image.png' }`

I also wrote my own ImageNodes plugin component to include within the Sigma component.  This adds the images and type at render time though, so it may not be ideal for performance.

```
const ImageNodes = props => {
  useEffect(() => {
    if (props.sigma {
      props.sigma.graph.nodes().forEach(node => {
        node.image = '/image.png'
        node.type = 'circle'
      })
    }
  }, [props])

  return null
}

export default ImageNodes
```

**Comment by jaredkirkley** [comment] 2019-10-24 14:03
@dunnock are you going to accept my PR for this fix?  I see you've worked on this project since this series of comments.  Please reply or make suggestions if you think my fix is not acceptable.

**Comment by dunnock** [comment] 2019-10-24 18:49
Many thanks @jaredkirkley, I really appreciate that you took your time and found the root cause. Though I left comment in the pull request suggesting little change so that your fix will also work in cases when NodeShapes plugin is not loaded. Thanks again

**Comment by jaredkirkley** [comment] 2019-10-24 19:20
@dunnock I'm not seeing any comments on the PR :(

Can you double check that the comment was posted?  I'd love to fix it up for you more!

Thanks for taking a look!

**Comment by dunnock** [comment] 2019-10-24 19:51
My bad, I forgot to press submit review.. you should see it now

**Comment by dunnock** [comment] 2019-10-25 21:06
@jaredkirkley  I have released your patch with 1.2.31, please confirm it works? Thanks

**Comment by dunnock** [comment] 2019-10-29 12:15
Closing this as since resolution no comments

**Closed by dunnock** 2019-10-29 12:15 UTC
